---
title: "Graphs"
author: "Acacia Tang"
date: "2024-07-12"
output: html_document
---
```{r, include=FALSE}
library(ggplot2)
library(readr)
library(car)
library(dunn.test)
```

### Load results
```{r}
setwd('/Users/acacia/gitrepo/TRACPATHStest')
testiTime <- read_csv('testi/Results/testi_time.csv')
testi <- read_csv('testi.csv')

testsizeTime <- read_csv('testsize/Results/testsize_time.csv')
testsize <- read_csv('testsize.csv')

testwindowTime <- read_csv('testwindow/Results/testwindow_time.csv')
testwindowTime$window = as.integer(testwindowTime$window)
testwindowTime = testwindowTime[testwindowTime$window < 50000,]
testwindow <- read_csv('testwindow.csv')
testwindow$testValue = as.integer(testwindow$testValue)
testwindow = testwindow[testwindow$testValue < 50000,]

testhzTime <- read_csv('testhz/Results/testhz_time.csv')
testhz <- read_csv('testhz.csv')

crall <- read_csv('testCrall.csv')
manual <- read_csv('fromFrames.csv')
```

### testi1 graphs
#### Time graph
```{r}
#testi
ggplot(testiTime, aes(x=i**2, y=seconds)) +
  geom_jitter(width=0.05, alpha=0.2)+geom_smooth(method='lm', se=TRUE, level=0.95) +
  xlab("Search area (ixi pixels)") + ylab("Processing time (s)") +
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

#testsize
ggplot(testsizeTime, aes(x=size**2, y=seconds)) +
  geom_jitter(width=0.005, alpha=0.2)+geom_smooth(method='lm', se=TRUE, level=0.95) +
  xlab("Square of scale relative to original") + ylab("Processing time (s)") +
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

#testwindow
ggplot(testwindowTime, aes(x=log(2*window), y=log(seconds))) +
  geom_jitter(width=0.005, alpha=0.2)+geom_smooth(method='lm', se=TRUE, level=0.95) +
  xlab("log(Frames processed)") + ylab("log(Processing time (s))") +
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


#testhz
ggplot(testhzTime, aes(x=30/`1/hz`, y=seconds))+
  geom_jitter(width=0.005, alpha=0.2)+geom_smooth(se=TRUE, level=0.95) +
  xlab("Frame rate (frames per second)") + ylab("Processing time (s)") +
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

```

#### Error graph
```{r}
ggplot(testi, aes(x=testValue, y=count, color=metric)) +
  geom_jitter(width = 0.05, alpha = 0.2)+geom_smooth(aes(fill=metric, se=TRUE, level=0.95)) +
  xlab("Search area (ixi pixels)") + 
  scale_y_continuous(name = "% Rate", sec.axis = sec_axis(~.*0.25, name="Number of False Positives")) + 
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


TP = testi[testi$metric == 'truePos',]
anovaModel <- aov(formula = count ~ testValue, data = TP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = TP)

##kruskal-wallis
kruskal.test(count ~ testValue, data = TP)

print(tapply(TP$count, TP$testValue, mean))
print(tapply(FN$count, FN$testValue, mean))
print(tapply(FP$count, FP$testValue, mean))
print(tapply(mislabel$count, mislabel$testValue, mean))

FN = testi[testi$metric == 'falseNeg',]
anovaModel <- aov(formula = count ~ testValue, data = FN)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = FN)

##kruskal-wallis
kruskal.test(count ~ testValue, data = FN)

print(tapply(FN$count, FN$testValue, mean))



FP = testi[testi$metric == 'falsePos',]
anovaModel <- aov(formula = count ~ testValue, data = FP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = FP)

print(tapply(FP$count, FP$testValue, mean))

ML = testi[testi$metric == 'mislabelled',]
anovaModel <- aov(formula = count ~ testValue, data = ML)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = ML)

print(tapply(ML$count, ML$testValue, mean))
```

```{r}
ggplot(testsize, aes(x=testValue/10, y=count, color=metric)) +
  geom_jitter(width = 0.005, alpha = 0.2)+geom_smooth(aes(fill=metric, se=TRUE, level=0.95)) +
  xlab("Scale relative to original") + 
  scale_y_continuous(name = "% relative to manual ID", sec.axis = sec_axis(~.*0.25, name="Number of False Positives")) + 
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


TP = testsize[testsize$metric == 'True Positive',]
anovaModel <- aov(formula = count ~ testValue, data = TP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = TP)

##kruskal-wallis
kruskal.test(count ~ testValue, data = TP)
dunn.test(TP$count, TP$testValue)

print(tapply(TP$count, TP$testValue, mean))

FN = testsize[testsize$metric == 'False Negative',]
anovaModel <- aov(formula = count ~ testValue, data = FN)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = FN)

##kruskal-wallis
kruskal.test(count ~ testValue, data = FN)
dunn.test(FN$count, FN$testValue)

print(tapply(FN$count, FN$testValue, mean))



FP = testsize[testsize$metric == 'False Positive',]
anovaModel <- aov(formula = count ~ testValue, data = FP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = FP)
dunn.test(FP$count, FP$testValue)

print(tapply(FP$count, FP$testValue, mean))

ML = testsize[testsize$metric == 'Mislabelling',]
anovaModel <- aov(formula = count ~ testValue, data = ML)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = ML)

print(tapply(ML$count, ML$testValue, mean))
```

```{r}
testwindow$testValue = testwindow$testValue*2
testwindow$testValue = as.factor(testwindow$testValue)
ggplot(testwindow, aes(x=testValue, y=count, color=metric, fill=metric)) +
  #geom_jitter(width = 0.005, alpha = 0.2)+geom_smooth(aes(fill=metric, se=TRUE, level=0.95)) +
  #geom_bar(stat='identity')+
  geom_boxplot(alpha = 0.1)+geom_point(alpha = 0.5, position=position_jitterdodge()) + 
  xlab("Frames processed") + 
  scale_y_continuous(name = "% Rate", sec.axis = sec_axis(~.*0.25, name="Number of False Positives")) + 
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())


TP = testwindow[testwindow$metric == 'True Positive',]
anovaModel <- aov(formula = count ~ testValue, data = TP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = TP)

##kruskal-wallis
kruskal.test(count ~ testValue, data = TP)
dunn.test(TP$count, TP$testValue)

print(tapply(TP$count, TP$testValue, mean))

FN = testwindow[testwindow$metric == 'False Negative',]
anovaModel <- aov(formula = count ~ testValue, data = FN)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = FN)

##kruskal-wallis
kruskal.test(count ~ testValue, data = FN)
dunn.test(FN$count, FN$testValue)

print(tapply(FN$count, FN$testValue, mean))



FP = testwindow[testwindow$metric == 'False Positive',]
anovaModel <- aov(formula = count ~ testValue, data = FP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = FP)
dunn.test(FP$count, FP$testValue)

print(tapply(FP$count, FP$testValue, mean))

ML = testwindow[testwindow$metric == 'Mislabelling',]
anovaModel <- aov(formula = count ~ testValue, data = ML)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = ML)

print(tapply(ML$count, ML$testValue, mean))
```

```{r}
ggplot(testhz, aes(x=30/testValue, y=count, color=metric)) +
  geom_jitter(width = 0.005, alpha = 0.2)+geom_smooth(aes(fill=metric, se=TRUE, level=0.95)) +
  #geom_bar(stat='identity')+
  xlab("Frame rate (frames per second)") + 
  scale_y_continuous(name = "% Rate", sec.axis = sec_axis(~.*0.25, name="Number of False Positives")) + 
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

TP = testhz[testhz$metric == 'True Positive',]
anovaModel <- aov(formula = count ~ testValue, data = TP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
#leveneTest(count ~ testValue, data = TP)

##kruskal-wallis
kruskal.test(count ~ testValue, data = TP)
print(tapply(TP$count, TP$testValue, mean))

FN = testhz[testhz$metric == 'False Negative',]
anovaModel <- aov(formula = count ~ testValue, data = FN)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))


##kruskal-wallis
kruskal.test(count ~ testValue, data = FN)

print(tapply(FN$count, FN$testValue, mean))


FP = testhz[testhz$metric == 'False Positive',]
anovaModel <- aov(formula = count ~ testValue, data = FP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
FP$groups = as.factor(FP$testValue)
leveneTest(count ~ groups, data = FP)

##kruskal-wallis
kruskal.test(count ~ testValue, data = FP)
dunn.test(FP$count, FP$testValue)

print(tapply(FP$count, FP$testValue, mean))

ML = testhz[testhz$metric == 'Mislabelling',]
anovaModel <- aov(formula = count ~ testValue, data = ML)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##kruskal-wallis
kruskal.test(count ~ testValue, data = ML)
dunn.test(ML$count, ML$testValue)
print(tapply(ML$count, ML$testValue, mean))
```

```{r}
#compare best of everything to manual video
TRAC <- testsize[testsize$testValue==10,]
TRAC$test = 'TRAC only'
PATHS <- testhz[testhz$testValue==1,]
PATHS$test = 'TRAC-PATHS'

plotme <- rbind(crall, TRAC, PATHS, manual)
plotme = plotme[plotme$metric != 'truePos',]

ggplot(data=plotme, aes(x=test, y=count, colour=metric, fill=metric))+
  geom_boxplot(alpha = 0.1)+geom_point(alpha = 0.5, position=position_jitterdodge()) + 
  xlab("Algorithm used") + 
  scale_y_continuous(name = "% Rate", sec.axis = sec_axis(~.*0.25, name="Number of False Positives")) + 
  theme(panel.background = element_rect(fill = "white", colour = 'black', linetype = 'solid'),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()
)


FN = plotme[plotme$metric == 'False Negative',]
FP = plotme[plotme$metric == 'False Positive',]
mislabel = plotme[plotme$metric == 'Mislabelling',]
TP = plotme[plotme$metric == 'True Positive',]

FN = tapply(FN$count, FN$test, mean)
FP = tapply(FP$count, FP$test, mean)
ML = tapply(mislabel$count, mislabel$test, mean)
TP = tapply(TP$count, TP$test, mean)

print(FN)
print(FP)
print(ML)
print(TP)
```

```{r}
#anovas

#FN
FN = plotme[plotme$metric == 'False Negative',]
anovaModel <- aov(formula = count ~ test, data = FN)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
leveneTest(count ~ test, data = FN)
print(summary(anovaModel))

#post-hoc t-test
TukeyHSD(anovaModel)
```

```{r}
#FP
FP = plotme[plotme$metric == 'False Positive',]
anovaModel <- aov(formula = count ~ test, data = FP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
hist(residuals(anovaModel))
##test homogeneity of variances
leveneTest(count ~ test, data = FP)

#kruskal-wallis
kruskal.test(count ~ test, data = FP)
dunn.test(FP$count, FP$test)
```

```{r}

#ML
ML = plotme[plotme$metric == 'Mislabelling',]
anovaModel <- aov(formula = count ~ test, data = ML)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
hist(residuals(anovaModel))
##test homogeneity of variances
leveneTest(count ~ test, data = ML)
print(summary(anovaModel))

##kruskal-wallis
kruskal.test(count ~ test, data = ML)
dunn.test(ML$count, ML$test)

```

```{r} 
#TP
TP = plotme[plotme$metric == 'True Positive',]
anovaModel <- aov(formula = count ~ test, data = TP)
##test normal distribution of dependent variable
shapiro.test(residuals(anovaModel))
qqnorm(residuals(anovaModel))
qqline(residuals(anovaModel))
##test homogeneity of variances
leveneTest(count ~ test, data = TP)

print(summary(anovaModel))
#post-hoc t-test
TukeyHSD(anovaModel)
```
