python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B1R2A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B5R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3B6R1C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B4R2C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R1C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D5R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B5R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D7R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1B1R1B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B6R2C2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D5R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D1R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R3D2R2D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2B2R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B2R2B2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R1D1R2A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R2D2R1A2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4B5R1D2 9&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 0&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 1&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 2&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 3&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 4&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 5&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 6&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 7&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 8&
python3 testhz.py /Users/acacia/Desktop/wranglePrep/wranglePreped/R4D6R2A2 9&
