# Python build file

universe = vanilla
log = interactive.log


# If building on CentOS 8 (Recommended)
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/chtc/el8/python39.tar.gz, http://proxy.chtc.wisc.edu/SQUID/ttang53/tracpaths.tar.gz, http://proxy.chtc.wisc.edu/SQUID/ttang53/testwindow.tar.gz
# Indicate which version of Linux (CentOS) you want to build your packages on
requirements = (OpSysMajorVer =?= 8) && (HasCHTCStaging == true)
request_cpus = 1
request_memory = 32GB
request_disk = 64GB

# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs) and your desired name of the HTCondor log file,
#  which is where HTCondor will describe what steps it takes to run 
#  your job. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
universe = vanilla
log = testwindow_$(Cluster).log

executable = testwindow/run.sh
arguments = $(folder) $(testvar) $(Process)
executable = testwindow/run.sh
output = testwindow_$(Cluster)_$(Process).out
error = testwindow_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue folder, testvar from testwindow/list.txt